import {StyleSheet} from 'react-native';
import {moderateScale} from 'react-native-size-matters';
import {COLORS, FONTS} from '../../../constants';
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  innerContainer: {
    flex: 1,
  },
  indicatorStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
  },
  cardStyle: {
    backgroundColor: COLORS.WHITE_SECONDARY,
    borderRadius: 8,
    width: '20%',
    marginHorizontal: 10,
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#171717',
    shadowOffset: {width: -5, height: 0},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
    padding: 5,
  },
  carImageStyle: {
    height: 60,
    width: 60,
  },
  headerContainer: {
    marginTop: 7,
  },
  cardService: {
    backgroundColor: COLORS.WHITE_SECONDARY,
    borderRadius: 8,
    width: '95%',
    marginHorizontal: 10,
    marginTop: 20,
    justifyContent: 'center',
    shadowColor: '#171717',
    shadowOffset: {width: -5, height: 0},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  carWashContainer: {
    marginTop: 15,
    backgroundColor: COLORS.WHITE_SECONDARY,
    marginHorizontal: 10,
    borderRadius: 8,
    paddingVertical: 10,
  },
  carWashInnerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 10,
    marginTop: 3,
  },
  cardInnerContainer: {
    marginHorizontal: 8,
  },
  cardDetailsStyle: {
    backgroundColor: COLORS.WHITE_SECONDARY,
    borderRadius: 8,
    width: '95%',
    flexDirection: 'row',
    marginHorizontal: 10,
    marginTop: 12,
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#171717',
    shadowOffset: {width: -5, height: 0},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  carNameTextStyle: {
    //
    // justifyContent: 'center',
    // alignItems: 'center',
    fontSize: 12,
    fontFamily: FONTS.POPPINS_MEDIUM,
    marginStart: 3,
    color: COLORS.PRIMARY_BLACK,
  },
  serviceTitleRemarks: {
    fontSize: 12,
    fontFamily: FONTS.POPPINS_SEMI_BOLD,
    marginStart: 3,
    color: COLORS.PRIMARY_BLACK,
  },
  notifyTextStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 10,
    marginTop: 40,
  },
  addBtnText: {
    marginHorizontal: 10,
    color: COLORS.WHITE,
  },
  carNumberTextStyle: {
    top: 20,
    fontSize: 10,
    fontFamily: FONTS.POPPINS_MEDIUM,
    marginStart: 3,
    lineHeight: 18,
    color: COLORS.PRIMARY_BLACK,
  },
  carRegisterationNumberTextStyle: {
    fontSize: 12,
    fontFamily: FONTS.POPPINS_REGULAR,
    marginStart: 3,
    lineHeight: 18,
    color: COLORS.PRIMARY_BLACK,
  },
  carTypeName: {
    fontSize: 12,
    fontFamily: FONTS.POPPINS_REGULAR,
    marginStart: 3,
    lineHeight: 18,
    color: COLORS.PRIMARY_BLACK,
  },
  btnNextContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: moderateScale(10),
    paddingBottom: 10,
  },
  btnNext: {
    width: '60%',
    marginTop: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnStyles: {
    backgroundColor: COLORS.ORANGE,
    padding: 10,
    borderRadius: 10,
    marginHorizontal: 10,
  },
  carWashSerContainer: {
    marginTop: 9.94,
  },
  serviceTextStyle: {
    fontSize: 14,
    color: COLORS.PRIMARY_BLACK,
    lineHeight: 21,
    marginHorizontal: 10,
    paddingVertical: 10,
    fontFamily: FONTS.POPPINS_MEDIUM,
  },
  remarkTextStyle: {
    height: moderateScale(80),
    borderWidth: 0.4,
    borderColor: COLORS.PRIMARY_GREY,
    borderRadius: 8,
    paddingHorizontal: 10,
    bottom: 10,
  },
  serviceDetailTextStyle: {
    fontSize: 12,
    color: COLORS.PRIMARY_BLACK,
    lineHeight: 18,
    fontFamily: FONTS.POPPINS_REGULAR,
    marginHorizontal: 10,
    paddingVertical: 8,
    bottom: 18,
    textAlign: 'justify',
  },
  carWashSerContainer: {
    marginTop: 30,
    marginHorizontal: 27,
  },
  carWashTextStyle: {
    fontSize: moderateScale(16),
    color: COLORS.PRIMARY_BLACK,
    lineHeight: 27,
    fontFamily: FONTS.POPPINS_SEMI_BOLD,
    maxWidth: 250,
  },
  carWashServiceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  borderStyle: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.ORANGE,
    marginHorizontal: 10,
  },
  carImageContainer: {
    marginEnd: 10,
  },
  lableContainer: {
    backgroundColor: COLORS.WHITE,
  },
  dropdown: {
    height: 50,
    width: '100%',
    borderColor: 'SECONDARY_BLACK',
    borderWidth: 0.5,
    borderRadius: 8,
    paddingHorizontal: 8,
    color: COLORS.PRIMARY_BLACK,
  },
  dropDownImageStyle: {
    width: 12,
    height: 12,
  },
  icon: {
    marginRight: 5,
  },
  label: {
    position: 'absolute',
    backgroundColor: COLORS.WHITE,
    left: 10,
    top: -8,
    zIndex: 999,
    paddingHorizontal: 8,
    fontSize: 12,
    borderRadius: 10,
    color: COLORS.PRIMARY_BLACK,
  },
  placeholderStyle: {
    fontSize: 12,
    fontFamily: 'Poppins',
    color: COLORS.PRIMARY_BLACK,
    paddingLeft: 8,
  },
  selectedTextStyle: {
    fontSize: 12,
    paddingLeft: 8,
    color: 'black',
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  starTextStyle: {
    color: COLORS.ORANGE,
  },
  renderItemContainer: {
    padding: 10,
    borderBottomWidth: 0.2,
    borderBottomColor: COLORS.ORANGE,
  },
  modal_id: {
    color: COLORS.PRIMARY_BLACK,
    fontSize: 12,
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  regNumber: {
    color: COLORS.ORANGE,
    fontSize: 10,
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  addButtonContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 40,
    marginTop: 40,
  },
  btnColored: {
    width: 140,
    bottom: 10,
  },
  mainContainer: {
    marginStart: 50,
  },
  remarkContainer: {
    marginHorizontal: 10,
    marginTop: 10,
  },
});
export default styles;
