export const ROUTES = {
  PROFILE: 'Profile',
  EDIT_PROFILE: 'EditProfile',
  HOME: 'Home',
  VEHICLES: 'Vehicles',
  ADD_VEHICLE: 'AddVehicle',
  ORDER_REPORTS: 'OrderReports',
  ORDER_REPORT_DETAIL: 'OrderReportDetail',
  LOGIN: 'Login',
  NOTIFICATIONS: 'Notifications',
  BOTTOM_TABS: 'BottomTabs',
  TIME_SLOTS: 'TimeSlots',
  SERVICE_DETAILS: 'ServiceDetails',
  ORDER_SUMMARY: 'OrderSummary',
  SEARCH_SERVICE_PROVIIDER: 'SearchServiceProvider',
  SEARCH_SERVICE_NOT_FOUND: 'SearchServiceNotFound',
  ORDER_PLACED: 'OrderPlaced',
  ADD_ADDRESS: 'AddAddress',
  ROOT: 'Root',
  ADD_ADDRESS_LIST: 'AddAddressList',
  SEARCH_ADDRESS: 'SearchAddress',
  GET_LOCATION: 'GetLocation',
  CONFIRM_LOCATION: 'ConfirmLocation',
  CATEGROIES_LIST: 'CategroiesList',
  UPDATE_VEHICLE: 'UpdateVehicle',
};
